### ISSUE TITLE
MQTT support doesn't seem to work

### ISSUE THREAD

**Issue by sarnau** [nDenerserve/SmartPi#17]
As soon as I enable MQTT support with 'mqtt_enabled=1' the system no longer starts up successfully.

Here is the section of the area. I use the latest version 0.5.8 from the home page.
```
[mqtt]
mqtt_enabled=1
mqtt_broker_url="192.168.178.62"
mqtt_broker_port="1883"
mqtt_username="pi"
mqtt_password="raspberry"
mqtt_topic="smartpi"
```

**Comment by Trickx** [comment]
Hi Markus,

I wrote the code to include MQTT support within SmartPi.
Since I’m using the SmartPi simply as sensor node and don’t make use of the lastest software release.
In the next days, I will update my system to the latest revision and will check for the issue.
Do you have any error messages available?

Regards,
Sven

**Comment by sarnau** [comment]
Hi,

Ok, if I launch smartpireadout with the above settings via ssh, it all work fine (MQTT are being send). However: once I reboot the Pi, the HTML interface on port 1080 no longer starts up correctly. Disabling MQTT via the enabled flag and another reboot and everything is fine again.

Modifying the config after the reboot and then launching another instance of smartpireadout also works. But because they share the config, it is not really a solution.

**Comment by Trickx** [comment]
Hi Markus,

greetings from Hanover to Hamburg :-)

I could reproduce your issue.
'smartpireadout' crashes if it can't connect to the MQTT broker.

- Are you able to start smartpireadout without any changes to the configuration manually?
`sudo /etc/init.d/smartpi stop` followed by
`sudo /etc/init.d/smartpi start`

  - If yes, your MQTT broker (most likely mosquitto) is not yet up and running when smartpi starts.
  - If not, your settings may not correct. Check your settings in the MQTT section in /etc/smartpi.

The solution is twofold:
1. Handle this kind of exceptions within readout.go accordingly. To be implemented...
The panic is currently being thrown in line 71.
2. Start smartpi after mosquitto on the RPI.
This is system dependend. On my system (emonpi) mosquitto is started via upstart rather than init.d scripts. Unfortunately smartpi makes use of init.d scripts.

**Comment by SuperQ** [comment]
Yea, there are ton `panic()` calls in this code that should really be handled better.  It's on my TODO list after I cleanup a few other things. 😄

**Comment by Trickx** [comment]
Today, I added logging to smartpireadout to get the root cause of the reported issue.
My RPI uses "systemd" to start daemons at boot time.
I configured mosquitto to start before smartpi, but without success.
Mosquitto takes some until incoming TCP connection are being accepted.
Unfortunately the mosquitto service already returns at this time, enabling smartpi to start.
This is why smartpireadout crashes when started at boot time.
The added logging function confirmed my assumption.
Furthermore, I rewrote MQTT connection handling to avoid crashes when the broker is not reachable.
It tries to connect each update cycle.
But unfortunately, latest commits broke readout of current and power values, see issue #27 
Once this is fixed, I will test my MQTT fix and publish the code.

**Comment by SuperQ** [comment]
I think this has been fixed thanks to MQTT retries that @Trickx added.

**Comment by Trickx** [comment]
I can confirm. Successfully tested on my system.

**Comment by gon0** [comment]
I have a similar problem: When MQTT is enabled, the web-interface does not work properly.
I have updated to the newest versions. In case the web-interface loads, I can read the version 2019.04.01-12:51:36
![Webinterface_working](https://user-images.githubusercontent.com/33236024/56056523-b6fe3c00-5d5c-11e9-8d2f-e7ce06e33849.png)

The I clicked on the settings-page: 
![Settings_Page](https://user-images.githubusercontent.com/33236024/56056551-cbdacf80-5d5c-11e9-8e9d-287b6519c907.png)
The settings page does not load correctly.

In most cases the webinterface looks like this:
![webinterface_not_working](https://user-images.githubusercontent.com/33236024/56056595-edd45200-5d5c-11e9-9497-c62bf344f793.png)

I then read this post and executed this command:
`pi@smartpi:~ $ sudo /etc/init.d/smartpi stop
hwclock: Cannot access the Hardware Clock via any known method.
hwclock: Use the --debug option to see the details of our search for an access method.`

Then I executed this command:
`sudo /etc/init.d/smartpi start`
After that, MQTT started working for the first time:
![MQTT_Runningpng](https://user-images.githubusercontent.com/33236024/56056662-24aa6800-5d5d-11e9-975f-f355642cbe8f.png)

Unfortunately, the webinterface still does not work. What can I do to get the webinterface AND MQTT to work?
